version: '3'

services:
  web:
    build: .
    volumes:
      - .:$PWD:delegated
    ports:
      - 3001:3001
    depends_on:
      - postgres
    working_dir: $PWD

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5552:5432
    environment:
      POSTGRES_PASSWORD: diesel_sandbox
      POSTGRES_USER: diesel_sandbox
